---

 - name: add key for docker repository
   become: yes
   apt_key: 
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower}}/gpg"
    state: "present"

 - name: add docker repository
   become: yes
   apt_repository: 
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower}} {{ansible_distribution_release}} stable"
    state: "present" 
    filename: "docker"
    update_cache: "yes"

 - name: install docker
   become: yes
   apt: 
    name: "docker-ce"
    state: "latest"
    force: yes
   notify: restart docker

 - name: start docker at boot time
   become: yes
   systemd: 
    name: "docker.service"
    enabled: yes
   notify: restart docker

 - name: adding docker user to group docker
   become: yes
   user: name='{{ docker_user }}' groups='docker' state=present append=yes
   
 - name: install docker-compose
   become: yes
   get_url: 
    url: "{{docker_compose_url}}"
    dest: "/usr/local/bin/docker-compose"
    mode: "u=rwx,g=rx,o=rx"